"""Add topic column to Chat model

Revision ID: 04c6d1bb0ba1
Revises: d0331d5b7624
Create Date: 2024-05-19 14:07:10.768804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c6d1bb0ba1'
down_revision = 'd0331d5b7624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=30), nullable=False, server_default='General'))

    # Remove the server default after adding the column
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('topic', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
